
// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

const int MIN_CHANNEL_NAME_LENGTH = 1;
const int MAX_CHANNEL_NAME_LENGTH = 64;
const String IGNORE_CHANNEL_MENTIONS_ON = 'on';
const String IGNORE_CHANNEL_MENTIONS_OFF = 'off';
const String IGNORE_CHANNEL_MENTIONS_DEFAULT = 'default';
const String CHANNEL_AUTO_FOLLOW_THREADS_TRUE = 'on';
const String CHANNEL_AUTO_FOLLOW_THREADS_FALSE = 'off';

final Map<String, dynamic> constants = {
    'IGNORE_CHANNEL_MENTIONS_ON': IGNORE_CHANNEL_MENTIONS_ON,
    'IGNORE_CHANNEL_MENTIONS_OFF': IGNORE_CHANNEL_MENTIONS_OFF,
    'IGNORE_CHANNEL_MENTIONS_DEFAULT': IGNORE_CHANNEL_MENTIONS_DEFAULT,
    'MAX_CHANNEL_NAME_LENGTH': MAX_CHANNEL_NAME_LENGTH,
    'MIN_CHANNEL_NAME_LENGTH': MIN_CHANNEL_NAME_LENGTH,
    'CHANNEL_AUTO_FOLLOW_THREADS_TRUE': CHANNEL_AUTO_FOLLOW_THREADS_TRUE,
    'CHANNEL_AUTO_FOLLOW_THREADS_FALSE': CHANNEL_AUTO_FOLLOW_THREADS_FALSE,
};
