// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

const List<String> DEFAULT_EMOJIS = [
'thumbsup',
'smiley',
'white_check_mark',
'heart',
'eyes',
'raised_hands',
];
const LARGE_ICON_SIZE = 32;
const LARGE_CONTAINER_SIZE = 48;
const REACTION_PICKER_HEIGHT = 48;
const REACTION_PICKER_MARGIN = 16;
const SMALL_CONTAINER_SIZE = 44;
const SMALL_ICON_BREAKPOINT = 410;
const SMALL_ICON_SIZE = 28;

final Map<String, dynamic> constants = {
'DEFAULT_EMOJIS': DEFAULT_EMOJIS,
'LARGE_ICON_SIZE': LARGE_ICON_SIZE,
'LARGE_CONTAINER_SIZE': LARGE_CONTAINER_SIZE,
'REACTION_PICKER_HEIGHT': REACTION_PICKER_HEIGHT,
'REACTION_PICKER_MARGIN': REACTION_PICKER_MARGIN,
'SMALL_CONTAINER_SIZE': SMALL_CONTAINER_SIZE,
'SMALL_ICON_BREAKPOINT': SMALL_ICON_BREAKPOINT,
'SMALL_ICON_SIZE': SMALL_ICON_SIZE,
};