// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

const String PUSH_PROXY_STATUS_VERIFIED = 'verified';
const String PUSH_PROXY_STATUS_UNKNOWN = 'unknown';
const String PUSH_PROXY_STATUS_NOT_AVAILABLE = 'not_available';

const String PUSH_PROXY_RESPONSE_VERIFIED = 'true';
const String PUSH_PROXY_RESPONSE_UNKNOWN = 'unknown';
const String PUSH_PROXY_RESPONSE_NOT_AVAILABLE = 'false';

final Map<String, String> pushProxy = {
  'PUSH_PROXY_STATUS_VERIFIED': PUSH_PROXY_STATUS_VERIFIED,
  'PUSH_PROXY_STATUS_UNKNOWN': PUSH_PROXY_STATUS_UNKNOWN,
  'PUSH_PROXY_STATUS_NOT_AVAILABLE': PUSH_PROXY_STATUS_NOT_AVAILABLE,
  'PUSH_PROXY_RESPONSE_VERIFIED': PUSH_PROXY_RESPONSE_VERIFIED,
  'PUSH_PROXY_RESPONSE_UNKNOWN': PUSH_PROXY_RESPONSE_UNKNOWN,
  'PUSH_PROXY_RESPONSE_NOT_AVAILABLE': PUSH_PROXY_RESPONSE_NOT_AVAILABLE,
};