// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import 'dart:io';

const int BOTTOM_TAB_HEIGHT = 52;
const double BOTTOM_TAB_ICON_SIZE = 31.2;
const int PROFILE_PICTURE_SIZE = 32;
const int PROFILE_PICTURE_EMOJI_SIZE = 28;

const int TEAM_SIDEBAR_WIDTH = 72;
const int TABLET_HEADER_HEIGHT = 44;
const int TABLET_SIDEBAR_WIDTH = 320;

const int STATUS_BAR_HEIGHT = 20;
const int DEFAULT_HEADER_HEIGHT = Platform.isAndroid ? 56 : 44;
const int LARGE_HEADER_TITLE_HEIGHT = 60;
const int SUBTITLE_HEIGHT = 24;
const int KEYBOARD_TRACKING_OFFSET = 72;

const int SEARCH_INPUT_HEIGHT = Platform.isAndroid ? 40 : 36;
const int SEARCH_INPUT_MARGIN = 5;

const int JOIN_CALL_BAR_HEIGHT = 40;
const int CURRENT_CALL_BAR_HEIGHT = 60;
const int CALL_ERROR_BAR_HEIGHT = 52;
const int CALL_NOTIFICATION_BAR_HEIGHT = 40;

const int ANNOUNCEMENT_BAR_HEIGHT = 40;

const Map<String, double> HOME_PADDING = {
    'paddingLeft': 18.0,
    'paddingRight': 20.0,
};

const Map<String, dynamic> defaults = {
    'BOTTOM_TAB_HEIGHT': BOTTOM_TAB_HEIGHT,
    'BOTTOM_TAB_ICON_SIZE': BOTTOM_TAB_ICON_SIZE,
    'PROFILE_PICTURE_SIZE': PROFILE_PICTURE_SIZE,
    'PROFILE_PICTURE_EMOJI_SIZE': PROFILE_PICTURE_EMOJI_SIZE,
    'DATA_SOURCE_USERS': 'users',
    'DATA_SOURCE_CHANNELS': 'channels',
    'DATA_SOURCE_DYNAMIC': 'dynamic',
    'SEARCH_INPUT_HEIGHT': SEARCH_INPUT_HEIGHT,
    'TABLET_SIDEBAR_WIDTH': TABLET_SIDEBAR_WIDTH,
    'TEAM_SIDEBAR_WIDTH': TEAM_SIDEBAR_WIDTH,
    'TABLET_HEADER_HEIGHT': TABLET_HEADER_HEIGHT,
    'STATUS_BAR_HEIGHT': STATUS_BAR_HEIGHT,
    'DEFAULT_HEADER_HEIGHT': DEFAULT_HEADER_HEIGHT,
    'LARGE_HEADER_TITLE_HEIGHT': LARGE_HEADER_TITLE_HEIGHT,
    'SUBTITLE_HEIGHT': SUBTITLE_HEIGHT,
    'KEYBOARD_TRACKING_OFFSET': KEYBOARD_TRACKING_OFFSET,
};
